name: Update TOC

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly (every Sunday)
  workflow_dispatch: # Allows manual execution

permissions:
  contents: write # Needed to push updates

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest WoW Classic Interface Version
        id: wow_version
        run: |
          # Fetch the latest interface version from Wowpedia or another reliable source
          INTERFACE=$(curl -s "https://wowpedia.fandom.com/api.php?action=parse&page=API_LatestInterface&format=json" | jq -r '.parse.text["*"]' | grep -oP 'Interface: \K[0-9]+')
          if [ -z "$INTERFACE" ]; then
            echo "Failed to fetch interface version" >&2
            exit 1
          fi
          echo "INTERFACE_VERSION=$INTERFACE" >> $GITHUB_ENV

      - name: Update TOC File
        run: |
          sed -i "s/## Interface: .*/## Interface: $INTERFACE_VERSION/" *.toc

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add *.toc && git commit -m "Update TOC to $INTERFACE_VERSION" && git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main)
